module.exports={
    ADMIN_COLLECTION:'admin',
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'user',
    CART_COLLECTION:'cart',
    CATAGORY_COLLECTION:'catagory',
    BRAND_COLLECTION:'brand',
    ORDER_COLLECTION:'order',
    WISHLIST_COLLECTION:'wishlist',
    BANNER_COLLECTION:'banner',
    COUPEN_COLLECTION:'coupen',
    OFFER_COLLECTION:'offer',
    PRODUCT_OFFER:'productoffer'
}